services:

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    restart: always

  odoo:
    build:
      context: ./odoo
      args:
        ODOO_VERSION: 19.0

    ports:
      - "8069:8069"
      - "5678:5678"

    volumes:
      - ./custom_addons:/mnt/extra-addons
      - ./odoo_src:/mnt/odoo
      - ./enterprise:/mnt/enterprise
      - ./odoo/odoo.conf:/etc/odoo/odoo.conf

    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo

    command: >
      bash -c "python3 -m debugpy --listen 0.0.0.0:5678 /usr/bin/odoo -c /etc/odoo/odoo.conf"
